language: python
install:
    - git clone https://github.com/thinca/vim-themis && (cd vim-themis && git show HEAD)
    - pip install vim-vint
before_script:
    - uname -a
    - vim --version
script:
    - vint --error --warning autoload/eightcc.vim autoload/eightcc/command.vim plugin/eightcc.vim --color
    - count=0; while true; do echo "${count} minutes..."; count=$(expr $count + 1); sleep 60; done &
    - time ./vim-themis/bin/themis test/
